name: Your New Jekyll Site
signature: "Yours truly, Grizzly Bear"
pygments: true
permalink: pretty
markdown: redcarpet
prose:
  siteurl: 'http://edrex.github.io'
  relativeLinks: 'http://edrex.github.io/links.json'
  media: 'media'
